spring.application.name=nutriMama

spring.datasource.url=jdbc:postgresql://ep-plain-sunset-axgy7t79-pooler.c-4.us-east-2.aws.neon.tech:5432/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_4QdyL7OUTYVw
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=${PORT:8081}



#spring.datasource.url=jdbc:mysql://localhost:3306/nutrimama?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&useServerPrepStmts=false
#spring.datasource.username=root
#spring.datasource.password=root
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#spring.jpa.properties.hibernate.use_sql_comments=false
#
#server.address=0.0.0.0
#server.port=8080

